# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_auto_20160323_0055'),
        ('Persons', '0002_auto_20160323_0055'),
        ('Users', '0004_auto_20160323_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favMovies',
            field=models.ManyToManyField(blank=True, to='Movies.Movie'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favPersons',
            field=models.ManyToManyField(blank=True, to='Persons.Person'),
        ),
    ]
