# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0001_initial'),
        ('Users', '0005_auto_20160323_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Images.ProfileImage'),
        ),
    ]
