# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nominations', '0002_nomination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
