# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0002_defaultimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Movies.Movie'),
        ),
    ]
