# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_auto_20160320_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 21, 5, 0, 12, 722034, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
