# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nominations', '0001_initial'),
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthDate', models.DateField()),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('pseudonym', models.CharField(blank=True, max_length=100)),
                ('partMovies', models.ManyToManyField(to='Movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, max_length=50)),
                ('screenTime', models.IntegerField(default=0)),
                ('nominations', models.ManyToManyField(to='Nominations.Nomination')),
            ],
        ),
        migrations.CreateModel(
            name='RolRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persons.Person')),
                ('roles', models.ManyToManyField(to='Persons.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='RolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rType', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='rol',
            name='rType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persons.RolType'),
        ),
    ]
