# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='partMovies',
            field=models.ManyToManyField(blank=True, to='Movies.Movie'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nominations',
            field=models.ManyToManyField(blank=True, to='Nominations.Nomination'),
        ),
        migrations.AlterField(
            model_name='rolrelation',
            name='roles',
            field=models.ManyToManyField(blank=True, to='Persons.Rol'),
        ),
    ]
