# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0001_initial'),
        ('Persons', '0002_auto_20160323_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='frontImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontImage', to='Images.PersonImage'),
        ),
    ]
