# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Persons', '0004_auto_20160325_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='rolRelation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Persons.RolRelation'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rolrelation',
            name='roles',
        ),
        migrations.AlterUniqueTogether(
            name='rolrelation',
            unique_together=set([('person', 'movie')]),
        ),
    ]
