# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movies', '0001_initial'),
        ('Users', '0001_initial'),
        ('Groups', '0001_initial'),
        ('Persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='movieInterest',
            field=models.ManyToManyField(to='Movies.Movie'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='personInterest',
            field=models.ManyToManyField(to='Persons.Person'),
        ),
    ]
