# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20160320_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Movies.MovieCategory'),
        ),
    ]
