# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_movie_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='frontImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontImage', to='Images.MovieImage'),
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
